# Generated by Django 2.2 on 2020-02-04 12:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tray',
            name='harvest_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
