# Generated by Django 2.2 on 2020-02-04 12:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0002_auto_20200204_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='tray',
            name='estimated_harvest_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='tray',
            name='estimated_yield',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
