# Generated by Django 2.2 on 2020-02-07 12:09

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0003_auto_20200204_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='family',
            field=models.CharField(max_length=100, validators=[django.core.validators.MaxLengthValidator(100)]),
        ),
        migrations.AlterField(
            model_name='crop',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MaxLengthValidator(100)]),
        ),
        migrations.AlterField(
            model_name='growthplan',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(50)]),
        ),
        migrations.AlterField(
            model_name='tray',
            name='estimated_harvest_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tray',
            name='estimated_yield',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tray',
            name='harvest_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tray',
            name='sow_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 7, 12, 9, 34, 660839, tzinfo=utc)),
        ),
    ]
