# Generated by Django 2.2 on 2020-02-07 17:19

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0004_auto_20200207_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutputDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.IntegerField()),
                ('units', models.IntegerField()),
                ('units_per_second', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='tray',
            name='sow_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 7, 17, 19, 24, 801793, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='OutputDeviceScheduledTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=None)),
                ('end_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('output_device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crop.OutputDevice')),
            ],
        ),
    ]
