# Generated by Django 2.2 on 2020-02-09 09:11

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0006_auto_20200207_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='outputdevice',
            name='name',
            field=models.CharField(default='', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='outputdevice',
            name='device_type',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator('^[{self.TYPE_GROW_LIGHT}, {self.TYPE_WATER_SPRAYER}]$', 'Not a valid type')]),
        ),
        migrations.AlterField(
            model_name='tray',
            name='sow_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 9, 9, 10, 54, 689225, tzinfo=utc)),
        ),
    ]
