# Generated by Django 2.2 on 2020-02-09 09:40

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0007_auto_20200209_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outputdevice',
            name='device_type',
            field=models.IntegerField(choices=[(1, 'Grow Light'), (2, 'Water Sprayer')]),
        ),
        migrations.AlterField(
            model_name='outputdevice',
            name='units',
            field=models.IntegerField(choices=[(1, 'Millilitres'), (2, 'Kilowatts')]),
        ),
        migrations.AlterField(
            model_name='outputdevicescheduledtask',
            name='end_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='outputdevicescheduledtask',
            name='output_device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='output_devices', to='crop.OutputDevice'),
        ),
        migrations.AlterField(
            model_name='outputdevicescheduledtask',
            name='start_time',
            field=models.TimeField(default=None),
        ),
        migrations.AlterField(
            model_name='tray',
            name='sow_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 9, 9, 40, 14, 783467, tzinfo=utc)),
        ),
    ]
