# Generated by Django 2.2 on 2020-02-09 16:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0008_auto_20200209_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outputdevicescheduledtask',
            name='output_device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='output_device_tasks', to='crop.OutputDevice'),
        ),
        migrations.AlterField(
            model_name='tray',
            name='sow_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
